# Generated by Django 4.2.2 on 2023-06-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutomuser', '0003_workday_archived_alter_application_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
