# Generated by Django 4.2.2 on 2023-06-11 16:43

import cutomuser.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cutomuser', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='job_id',
        ),
        migrations.AddField(
            model_name='application',
            name='date_time_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(auto_now_add=True, validators=[cutomuser.validators.validate_work_day]),
        ),
    ]
