# Generated by Django 4.2.2 on 2023-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutomuser', '0004_remove_workday_job_id_application_date_time_applied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='time_in',
            new_name='current_time',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='time_out',
        ),
        migrations.AddField(
            model_name='workday',
            name='check_out',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
