# Generated by Django 4.2.2 on 2023-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutomuser', '0005_alter_application_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slots',
            field=models.IntegerField(null=True),
        ),
    ]
