# Generated by Django 4.2.2 on 2023-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutomuser', '0006_job_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='archived',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
