# Generated by Django 4.2.2 on 2023-06-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutomuser', '0007_alter_application_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
